# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\work\compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\work\compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\work\compiler\CMakeFiles D:\work\compiler\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\work\compiler\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clox

# Build rule for target.
clox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clox
.PHONY : clox

# fast build rule for target.
clox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/build
.PHONY : clox/fast

c/chunk.obj: c/chunk.c.obj
.PHONY : c/chunk.obj

# target to build an object file
c/chunk.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/chunk.c.obj
.PHONY : c/chunk.c.obj

c/chunk.i: c/chunk.c.i
.PHONY : c/chunk.i

# target to preprocess a source file
c/chunk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/chunk.c.i
.PHONY : c/chunk.c.i

c/chunk.s: c/chunk.c.s
.PHONY : c/chunk.s

# target to generate assembly for a file
c/chunk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/chunk.c.s
.PHONY : c/chunk.c.s

c/compiler.obj: c/compiler.c.obj
.PHONY : c/compiler.obj

# target to build an object file
c/compiler.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/compiler.c.obj
.PHONY : c/compiler.c.obj

c/compiler.i: c/compiler.c.i
.PHONY : c/compiler.i

# target to preprocess a source file
c/compiler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/compiler.c.i
.PHONY : c/compiler.c.i

c/compiler.s: c/compiler.c.s
.PHONY : c/compiler.s

# target to generate assembly for a file
c/compiler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/compiler.c.s
.PHONY : c/compiler.c.s

c/debug.obj: c/debug.c.obj
.PHONY : c/debug.obj

# target to build an object file
c/debug.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/debug.c.obj
.PHONY : c/debug.c.obj

c/debug.i: c/debug.c.i
.PHONY : c/debug.i

# target to preprocess a source file
c/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/debug.c.i
.PHONY : c/debug.c.i

c/debug.s: c/debug.c.s
.PHONY : c/debug.s

# target to generate assembly for a file
c/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/debug.c.s
.PHONY : c/debug.c.s

c/main.obj: c/main.c.obj
.PHONY : c/main.obj

# target to build an object file
c/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/main.c.obj
.PHONY : c/main.c.obj

c/main.i: c/main.c.i
.PHONY : c/main.i

# target to preprocess a source file
c/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/main.c.i
.PHONY : c/main.c.i

c/main.s: c/main.c.s
.PHONY : c/main.s

# target to generate assembly for a file
c/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/main.c.s
.PHONY : c/main.c.s

c/memory.obj: c/memory.c.obj
.PHONY : c/memory.obj

# target to build an object file
c/memory.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/memory.c.obj
.PHONY : c/memory.c.obj

c/memory.i: c/memory.c.i
.PHONY : c/memory.i

# target to preprocess a source file
c/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/memory.c.i
.PHONY : c/memory.c.i

c/memory.s: c/memory.c.s
.PHONY : c/memory.s

# target to generate assembly for a file
c/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/memory.c.s
.PHONY : c/memory.c.s

c/scanner.obj: c/scanner.c.obj
.PHONY : c/scanner.obj

# target to build an object file
c/scanner.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/scanner.c.obj
.PHONY : c/scanner.c.obj

c/scanner.i: c/scanner.c.i
.PHONY : c/scanner.i

# target to preprocess a source file
c/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/scanner.c.i
.PHONY : c/scanner.c.i

c/scanner.s: c/scanner.c.s
.PHONY : c/scanner.s

# target to generate assembly for a file
c/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/scanner.c.s
.PHONY : c/scanner.c.s

c/value.obj: c/value.c.obj
.PHONY : c/value.obj

# target to build an object file
c/value.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/value.c.obj
.PHONY : c/value.c.obj

c/value.i: c/value.c.i
.PHONY : c/value.i

# target to preprocess a source file
c/value.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/value.c.i
.PHONY : c/value.c.i

c/value.s: c/value.c.s
.PHONY : c/value.s

# target to generate assembly for a file
c/value.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/value.c.s
.PHONY : c/value.c.s

c/vm.obj: c/vm.c.obj
.PHONY : c/vm.obj

# target to build an object file
c/vm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/vm.c.obj
.PHONY : c/vm.c.obj

c/vm.i: c/vm.c.i
.PHONY : c/vm.i

# target to preprocess a source file
c/vm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/vm.c.i
.PHONY : c/vm.c.i

c/vm.s: c/vm.c.s
.PHONY : c/vm.s

# target to generate assembly for a file
c/vm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clox.dir\build.make CMakeFiles/clox.dir/c/vm.c.s
.PHONY : c/vm.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... clox
	@echo ... c/chunk.obj
	@echo ... c/chunk.i
	@echo ... c/chunk.s
	@echo ... c/compiler.obj
	@echo ... c/compiler.i
	@echo ... c/compiler.s
	@echo ... c/debug.obj
	@echo ... c/debug.i
	@echo ... c/debug.s
	@echo ... c/main.obj
	@echo ... c/main.i
	@echo ... c/main.s
	@echo ... c/memory.obj
	@echo ... c/memory.i
	@echo ... c/memory.s
	@echo ... c/scanner.obj
	@echo ... c/scanner.i
	@echo ... c/scanner.s
	@echo ... c/value.obj
	@echo ... c/value.i
	@echo ... c/value.s
	@echo ... c/vm.obj
	@echo ... c/vm.i
	@echo ... c/vm.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

