# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run coverage
      - run: npx tsc
    # - name: Deploy to Github Pages
    # uses: JamesIves/github-pages-deploy-action@3.7.1
    # with:
    # GITHUB_TOKEN: ${{ secrets.EXCEL_ACCESS_TOKEN }}
    # BRANCH: gh-pages # The branch the action should deploy to.
    # FOLDER: dist # The folder the action should deploy.
    # CLEAN: true # Automatically remove deleted files from the deploy branch
